1. Impement Union, Intersection, Complement and Difference operations on fuzzy sets.
2. Also create fuzzy relation by Cartesian product of any two fuzzy sets and perform max-min composition on any two fuzzy relations.

In [1]:
import numpy as np
import pandas as pd

In [2]:
def union(R, S):
  Y = dict()
  i = 1
  for x,y in zip(R,S):
    key = "z"+str(i)
    # Finding max degree of membership between the two
    if R[x] > S[y]:
      Y[key] = R[x]
    else:
      Y[key] = S[y]
    i += 1
  return Y

In [3]:
def intersection(R, S):
  Y = dict()
  i = 1
  for x,y in zip(R,S):
    key = "z"+str(i)
    # Finding min degree of membership between the two
    if R[x] < S[y]:
      Y[key] = R[x]
    else:
      Y[key] = S[y]
    i += 1
  return Y

In [4]:
def complement(D):
  Y = dict()
  i = 1
  for k,v in D.items():
    key = "z"+str(i)
    # Finding complement of degree of membership
    Y[key] = 1 - v
    i += 1
  return Y

In [5]:
def difference(R, S):
  Y = dict()
  i = 1
  for x,y in zip(R,S):
    key = "z"+str(i)
    # Finding min between degree of membership of R and complement of S (u(R) n ~u(S))
    if R[x] < (1-S[y]):
      Y[key] = R[x]
    else:
      Y[key] = (1-S[y])
    i += 1
  return Y

In [6]:
def relation(R, S):
  arrL = list()

  for k,v in S.items():
    # Product for x1 in R
    if R['x1'] < v:
      arrL.append(R['x1'])
    else:
      arrL.append(v)
  arr = np.array(arrL)
  arrL.clear()

  for k1,v1 in R.items():
    # Product for remaining elements in set R
    if k1 == 'x1':
      continue
    for k,v in S.items():
      if v1 < v:
        arrL.append(v1)
      else:
        arrL.append(v)
    # Add row to array
    arr = np.vstack([arr, arrL])
    # Clear temp list
    arrL.clear()
  return arr

In [7]:
def composition(R, S):
  # Fetching the dimensions of R (X, Y) and S (Y, Z)
  Rrow, Rcol = R.shape
  Srow, Scol = S.shape

  # Creating empty array to store the composition with 1 row and Scol (Z) columns
  arr = np.empty((1,Scol))
  # Temp array to hold the elements of a row in arr
  arrL = list()
  # Temp array to hold all the min elements
  min = list()

  for i in range(0, Rrow):
    for j in range(0, Scol):
      for k in range(0,Rcol):
        # Comparison to find the min
        if R[i][k] < S[k][j]:
          min.append(R[i][k])
        else:
          min.append(S[k][j])
      # Sort min array to find the max
      min.sort(reverse=True)
      # Add max element to temp row array
      arrL.append(min[0])
      min.clear()
    # Add temp row array o composition
    arr = np.vstack([arr, arrL])
    arrL.clear()
  arr = np.delete(arr,0,0)
  return arr

In [8]:
R = dict()
S = dict()

R = {"x1": 0.3, "x2": 0.4, "x3": 0.5, "x4": 0.3}
S = {"y1": 0.2, "y2": 0.1, "y3": 0.2, "y4": 0.5}

print("R : ",R)
print("S : ",S)

print("\n")

RUS = dict()
RUS = union(R,S)
print("Union")
print("R U S : ", RUS)

print("\n")

RnS = dict()
RnS = intersection(R,S)
print("Intersection")
print("R n S : ", RnS)

print("\n")

cR = dict()
cR = complement(R)
print("Complement")
print("~R : ", cR)
cS = dict()
cS = complement(S)
print("~S : ", cS)

print("\n")

RmS = dict()
RmS = difference(R,S)
print("Difference")
print("R \ S : ", RmS)

print("\n")

RxS = relation(R,S)
print("Cartesian Product (Fuzzy Relation)")
print("R x S : ")
for row in RxS:
  print(row)

R :  {'x1': 0.3, 'x2': 0.4, 'x3': 0.5, 'x4': 0.3}
S :  {'y1': 0.2, 'y2': 0.1, 'y3': 0.2, 'y4': 0.5}


Union
R U S :  {'z1': 0.3, 'z2': 0.4, 'z3': 0.5, 'z4': 0.5}


Intersection
R n S :  {'z1': 0.2, 'z2': 0.1, 'z3': 0.2, 'z4': 0.3}


Complement
~R :  {'z1': 0.7, 'z2': 0.6, 'z3': 0.5, 'z4': 0.7}
~S :  {'z1': 0.8, 'z2': 0.9, 'z3': 0.8, 'z4': 0.5}


Difference
R \ S :  {'z1': 0.3, 'z2': 0.4, 'z3': 0.5, 'z4': 0.3}


Cartesian Product (Fuzzy Relation)
R x S : 
[0.2 0.1 0.2 0.3]
[0.2 0.1 0.2 0.4]
[0.2 0.1 0.2 0.5]
[0.2 0.1 0.2 0.3]


In [9]:
print("Consider two relations")
print('R(XxY) : ')
Rxy = np.array([[0.7, 0.5], [0.8, 0.4]])
print(Rxy)
print("\n")
print('S(YxZ) : ')
Syz = np.array([[0.9, 0.6, 0.2], [0.1, 0.7, 0.5]])
print(Syz)
print("\n")
RoS = composition(Rxy,Syz)
print("Composition")
print("R o S : ")
for row in RoS:
  print(row)

Consider two relations
R(XxY) : 
[[0.7 0.5]
 [0.8 0.4]]


S(YxZ) : 
[[0.9 0.6 0.2]
 [0.1 0.7 0.5]]


Composition
R o S : 
[0.7 0.6 0.5]
[0.8 0.6 0.4]
